#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Supply filename as argument"
else
  filepath=$(realpath $1)
  directory=$(dirname $filepath)
  filename=$(basename -- "$filepath")
  extension="${filename##*.}"
  filename="${filename%.*}"
  echo "$filename"
  #while true; do
    #inotifywait -e CLOSE_WRITE $filepath;
    #asy --render 0 $filename -o "";
  #done
fi

