#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Supply filename as argument"
else
  filepath=$(realpath $1)
  directory=$(dirname $filepath)
  filename=$(basename -- "$filepath")
  extension="${filename##*.}"
  filename="${filename%.*}"
  outfile="$directory/$filename.eps"
  asy --render 0 $filepath -o $outfile;
  xdg-open $outfile;
  while true; do
    inotifywait -e CLOSE_WRITE $filepath;
    asy --render 0 $filepath -o $outfile;
  done
fi

