module.exports = {
  extensions: ['tex2jax.js'],
  jax: ['input/TeX','output/HTML-CSS'],
  messageStyle: 'none',
  tex2jax: {
    displayMath: [
      ['$$\n', '\n$$'],
      ['$$\r\n', '\r\n$$']
    ],
    inlineMath: [
      ['$', '$'],
      ['$$', '$$']
    ],
    processEscapes: true,
    processEnvironments: false
  },
  TeX: {
    extensions: ["noUndefined.js", "autoload-all.js",
      "AMSmath.js", "AMSsymbols.js"
    ],
    Macros: {
      NN: "{\\mathbb{N}}",
      RR: "{\\mathbb{R}}",
      ZZ: "{\\mathbb{Z}}",
      CC: "{\\mathbb{C}}",
      QQ: "{\\mathbb{Q}}",
      CC: "{\\mathbb{C}}",
      RP: "{\\mathbb{RP}}",
      CP: "{\\mathbb{CP}}",
      HP: "{\\mathbb{HP}}",
      OP: "{\\mathbb{OP}}",
      FF: "{\\mathbb{F}}",
      PP: "{\\mathbb{P}}",
      AA: "{\\mathbb{A}}",
      MM: "{\\mathbb{M}}",
      TT: "{\\mathbb{T}}",
      SS: "{\\mathbb{S}}",
      KK: "{\\mathbb{K}}",
      Gr: "{\\text{Gr}}",
      GL: "{\\text{GL}}",
      char: "{\\mathbb{1}}",
      abs: ['\\left\\lvert #2 \\right\\rvert_{\\text{#1}}', 2, ""],
      Aut: "{\\text{Aut}}",
      del: '{\\partial}',
      too: ['{\\xrightarrow{#1}}', 1, ""],
      im: '{\\text{im}~}',
      homotopic: '\\simeq',
      into: '\\to',
      theset: ['\\{{#1}\\}', 1],
      norm: ['{\\lVert}{#1}{\\rVert}', 1],
      cross: '\\times',
      definedas: '\\mathrel{\\vcenter{:}}=',
      surjects: '\\twoheadrightarrow',
      onto: '\\twoheadrightarrow',
      injects: '\\hookrightarrow',
      id: '\\text{id}',
      restrictionof: ['\\left.{#1}\\right|_{#2}', 2],
      intersect: '\\bigcap',
      union: '\\bigcup',
      mapsvia: ['\\xrightarrow{#1}', 1],
      coker: '\\operatorname{coker}',
      tensor: '\\otimes',
      semidirect: '\\rtimes',
      pt: '\\{\\text{pt}\\}',
      and: '{\\text{and}}',
      or: '{\\text{or}}',
      bd: '{\\del}',
      wait: '{\\,\\cdot\\,}',
      selfmap: '{\\circlearrowleft}',
      tor: '{\\text{Tor}}',
      ext: '{\\text{Ext}}',
      hom: '{\\text{Hom}}',
      actson: '{\\curvearrowright}',
      actsonl: '{\\curvearrowleft}',
      disjoint: '{\\coprod}',
      qed: '{\\tag*{$\\blacksquare$}}',
			endef: '{\\tag*{$\\triangleleft$}}',
      dash: '{\\hbox{-}}',
      inner: ['\\langle #1, #2 \\rangle', 2, ""],
      bigast: '{\\mathop{\\Large \\ast}}',
      from: '{\\leftarrow}',
      covers: '{\\twoheadrightarrow_p}',
      suchthat: '{\\ni}',
      divides: '{\~\\mid\~}'
    }
  },
  'HTML-CSS': { availableFonts: ['TeX'] }
}
